/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenTokenIdRouteImport } from './routes/token.$tokenId'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenTokenIdRoute = TokenTokenIdRouteImport.update({
  id: '/token/$tokenId',
  path: '/token/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/launch': typeof LaunchRoute
  '/portfolio': typeof PortfolioRoute
  '/signin': typeof SigninRoute
  '/transactions': typeof TransactionsRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/launch': typeof LaunchRoute
  '/portfolio': typeof PortfolioRoute
  '/signin': typeof SigninRoute
  '/transactions': typeof TransactionsRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/launch': typeof LaunchRoute
  '/portfolio': typeof PortfolioRoute
  '/signin': typeof SigninRoute
  '/transactions': typeof TransactionsRoute
  '/token/$tokenId': typeof TokenTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/feed'
    | '/launch'
    | '/portfolio'
    | '/signin'
    | '/transactions'
    | '/token/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/feed'
    | '/launch'
    | '/portfolio'
    | '/signin'
    | '/transactions'
    | '/token/$tokenId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/feed'
    | '/launch'
    | '/portfolio'
    | '/signin'
    | '/transactions'
    | '/token/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  LaunchRoute: typeof LaunchRoute
  PortfolioRoute: typeof PortfolioRoute
  SigninRoute: typeof SigninRoute
  TransactionsRoute: typeof TransactionsRoute
  TokenTokenIdRoute: typeof TokenTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$tokenId': {
      id: '/token/$tokenId'
      path: '/token/$tokenId'
      fullPath: '/token/$tokenId'
      preLoaderRoute: typeof TokenTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  LaunchRoute: LaunchRoute,
  PortfolioRoute: PortfolioRoute,
  SigninRoute: SigninRoute,
  TransactionsRoute: TransactionsRoute,
  TokenTokenIdRoute: TokenTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
